spring:
  application:
    name: '@project.name@'
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /

# Management endpoints actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - metrics
          - info
  metrics:
    enable:
      jvm.memory.used: true
      process.uptime: true
      jdbc.connections.active: true
      process.cpu.usage: true
      all: false

# Gerenciador de Secrets
book:
  jwt:
    secret : asjndflkjaslkdjasslkd